Don't make floats FAST for now
Tantivy 0.10 allows setting the flag for f64 fields but crashes
when merging since it doesn't actually support it with:

> thread 'mergingthread-0' panicked at 'Failed to find a reader for single
> fast field. This is a tantivy bug and it should never happen.',